backend:
  name: git-gateway
  branch: portfolio
  commit_messages:
    create: 'chore(Content): Create {{collection}} “{{slug}}”'
    update: 'chore(Content): Update {{collection}} “{{slug}}”'
    delete: 'chore(Content): Delete {{collection}} “{{slug}}”'
    uploadMedia: 'chore(Content): Upload “{{path}}”'
    deleteMedia: 'chore(Content): Delete “{{path}}”'
    openAuthoring: '{{message}}'

local_backend: true

logo_url: /favicon.svg

media_folder: static/images
public_folder: /images

collections:
  - &service
    name: 'services___ru'
    label: 'Services (RU)'
    format: 'json'
    folder: 'content/ru/services'
    slug: '{{fields.slug}}'
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Slug (URL)"
        name: "slug"
        widget: "string"
      - label: "Call-to-Action"
        name: "cta"
        widget: "string"
      - label: "Homepage Description"
        name: "home_description"
        widget: "markdown"
      - label: "Excerpt"
        name: "excerpt"
        widget: "markdown"
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Meta Description"
        name: "meta_description"
        widget: "text"
  - <<: *service
    name: 'services___en'
    label: 'Services (EN)'
    folder: 'content/en/services'

  - &project
    name: 'projects___ru'
    label: 'Projects (RU)'
    folder: 'content/ru/projects'
    slug: '{{fields.slug}}'
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Slug (URL)"
        name: "slug"
        widget: "string"
      - label: "Description"
        name: "description"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Slides"
        name: "slides"
        required: false
        widget: "image"
        media_library:
        config:
          multiple: true
      - label: "Technologies"
        name: "technologies"
        required: false
        widget: "list"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Slug"
            name: "slug"
            widget: "string"
      - label: "Year"
        name: "year"
        required: false
        widget: "select"
        options: ["2017", "2018", "2019", "2020", "2021", "2022"]
      - label: "Link"
        name: "link"
        required: false
        widget: "string"
      - label: "Upfront"
        name: "upfront"
        widget: "relation"
        collection: "projects___ru"
        valueField: "slug"
        searchFields:
          - "title"
