backend:
  name: git-gateway
  branch: netlify-cms

logo_url: /favicon.svg

media_folder: static/img
public_folder: /img

collections:
  - &service
    name: 'services___ru'
    label: 'Services (RU)'
    format: 'json'
    folder: 'assets/content/services/ru'
    slug: '{{fields.slug}}'
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Slug (URL)"
        name: "slug"
        widget: "string"
      - label: "Homepage Description"
        name: "home_description"
        widget: "markdown"
  - <<: *service
    name: 'services___en'
    label: 'Services (EN)'
    folder: 'assets/content/services/en'

