backend:
  name: git-gateway
  branch: netlify-cms

logo_url: /favicon.svg

media_folder: static/img
public_folder: /img

collections:
  - name: 'services'
    label: 'Services'
    format: 'json'
    folder: 'assets/content/ru/services'
    slug: '{{fields.slug}}'
    create: true
    fields: &service
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Slug (URL)"
        name: "slug"
        widget: "string"
      - label: "Homepage Description"
        name: "home_description"
        widget: "markdown"
